//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengePapaBobsSi.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaCrust
    {
        public System.Guid PizzaCrustId { get; set; }
        public string PizzaCrustType { get; set; }
        public decimal PizzaCrustPrice { get; set; }
    }
}
