//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengePapaBobsSi.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaSize
    {
        public System.Guid PizzaSizeId { get; set; }
        public string PizzaSizeName { get; set; }
        public string PizzaSizeDesc { get; set; }
        public decimal PizzaSizePrice { get; set; }
    }
}
