//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengePapaBobsSi.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaTopping
    {
        public System.Guid PizzaToppingId { get; set; }
        public string PizzaToppingName { get; set; }
        public decimal PizzaToppingPrice { get; set; }
    }
}
